[package]
name = "joshuaclarkelua/knit"
description = "(FORKED) Knit is a lightweight game framework"
version = "1.7.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Comm = "joshuaclarkelua/comm@^1.0"
Promise = "joshuaclarkelua/promise@^4"
